api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('blogs/', views.BlogApiView.as_view(), name='blogs'),
    path('blogs/<int:pk>/', views.BlogApiView.as_view(), name='blog'),
    path('products/', views.ShopApiView.as_view(), name='products'),
    path('products/<int:pk>/', views.ShopApiView.as_view(), name='product')
]

mysite/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls")),
    path("shop/", include("shop.urls")),
    path("order/", include("order.urls")),
    path("core/", include("core.urls")),
    path("user/", include("user.urls")),
    path("rosetta", include('rosetta.urls')),
    path('api/', include('api.urls')),
    prefix_default_language=False
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('shop/', views.shop, name='shop'),  
    path('productdetails/<int:pk>/', views.product_details, name='product_details'),
    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('wishlist_view/<int:pk>/', views.wishlist_view, name='wishlist_view'),
    path('deletewishlist/<int:pk>/', views.remove_wishlist_product, name='remove_wishlist_product'),
    path('deletecart/<int:pk>/', views.remove_cart_product, name='remove_cart_product')
]

shop/models.py
from django.db import models

from user.models import User
from mysite.utils.base import BaseModel

class Color(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Manufacturer(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Tag(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Image(BaseModel):
    image = models.ImageField(max_length=100)

    def __str__(self):
        return f'{self.pk}'

class Category(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class product(BaseModel):
    AVAILABILITY = (('In stock', 'In stock'), ('Out of stock', 'Out of stock'))

    title = models.CharField(max_length=255, verbose_name='Title of your product', help_text='Max character limit 255')
    price = models.IntegerField()
    desc = models.TextField(verbose_name='Your description')
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, verbose_name='Manufacturer')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Category')
    availability = models.CharField(choices=AVAILABILITY)
    tag = models.ManyToManyField(Tag, verbose_name='Tag of your product')

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'All products'

    def __str__(self):
        return self.title



class product_version(BaseModel):
    color = models.ForeignKey(Color, on_delete=models.CASCADE, related_name="product_color")
    product = models.ForeignKey(product, on_delete=models.CASCADE, related_name="product_version")
    images = models.ManyToManyField(Image, related_name='images_of_products')
    cover_image = models.ImageField()
    date = models.DateTimeField(auto_now_add=True, verbose_name='Date')

    def __str__(self):
        return f"{self.product.title}'s {self.color.name} version"
    

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='wishlist')
    product = models.ForeignKey(product_version, on_delete=models.CASCADE, related_name='product_wishlist')
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = 'Wishlist'
        verbose_name_plural = 'Wishlists'

    def str(self):
        return self.product.product.title


class Add_to_Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='add_to_cart')
    product = models.ForeignKey(product_version, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


    class Meta:
        verbose_name = 'Add to Cart'
        verbose_name_plural = 'Add to Carts'

    def str(self):
        return self.product.product.title


class Review(BaseModel):
    Rates = {
        (1, "20"),
        (2, "40"),
        (3, "60"),
        (4, "80"),
        (5, "100")
    }

    products = models.ForeignKey(product_version, related_name='Reviews', on_delete=models.CASCADE)
    nickname = models.CharField(max_length=200)
    review = models.TextField()
    price_review = models.IntegerField(choices=Rates)
    value_review = models.IntegerField(choices=Rates)
    quality_review = models.IntegerField(choices=Rates)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.products.product.title, self.nickname)
    
    class Meta:
        verbose_name = "Product Review"
        verbose_name_plural = "Product Reviews"

shop/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ['price_review', 'value_review', 'quality_review', 'nickname', 'review']
        widgets = {
            'nickname': forms.TextInput(attrs={'class': 'form-group'}),
            'review' : forms.Textarea(attrs={'class': 'form-group'}),
        }

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import *
from .forms import ReviewForm



def shop(request):
    allproduct = product_version.objects.order_by('-created').distinct()
    manufacturer = Manufacturer.objects.all()
    color = Color.objects.all()
    tag = Tag.objects.all()
    category = Category.objects.all()

    p = Paginator(product_version.objects.all(), 4)
    page = request.GET.get('page')
    page_number = p.get_page(page)

    manufacturer_id = request.GET.get('manufacturer')
    color_id = request.GET.get('color')
    tags_id = request.GET.get('tag')
    category_id = request.GET.get('category')

    if color_id:
        page_number = product_version.objects.filter(color = color_id)
    elif manufacturer_id:
        page_number = product_version.objects.filter(product__manufacturer = manufacturer_id)
    elif tags_id:
        page_number = product_version.objects.filter(product__tag = tags_id)
    elif category_id:
        page_number = product_version.objects.filter(product__category = category_id)
    else:
        allproduct = product_version.objects.all()

    context = {
        'all' : allproduct,
        'manufacturer': manufacturer,
        'color' : color,
        'tag' : tag,
        'category': category,
        'page_number': page_number
    }
    return render(request, 'shop.html', context=context)





def product_details(request, pk):
    products = product_version.objects.filter(pk=pk).first()
    reviews = Review.objects.filter(products__pk=pk).all()
    tags = Tag.objects.all()
    image = Image.objects.all()
    colors = Color.objects.all()
    product_colors = []
    for color in colors:
        if products.product.pk == color.product_color.first().product.pk:
            product_colors.append({'color': color, 'pk': color.product_color.all().first().pk})
    print(product_colors)
    
    form = ReviewForm()

    color_id = request.GET.get('color')
    tags_id = request.GET.get('tags')

    if tags_id:
        products = Tag.objects.filter(tag = tags_id)
    elif color_id:
        products = Color.objects.filter(color = color_id)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.products = products
            review.save()
            return redirect('product_details', pk=pk)
    else:
        form = ReviewForm()

    context = {
        'product': products,
        'reviews': reviews,
        'form': form,
        'tags' : tags,
        'image': image,
        'colors': product_colors
        
    }
    return render(request, 'product-details.html', context=context)



@login_required(login_url='login')
def wishlist_view(request, pk):
    product = product_version.objects.get(id=pk)
    choosen, created = Wishlist.objects.get_or_create(user = request.user, product=product)

    if not created:
        choosen.quantity += 1
        choosen.save()
    return redirect('shop')

@login_required(login_url='login')
def add_to_cart(request, pk):
    product = product_version.objects.get(id=pk)
    cart, created = Add_to_Cart.objects.get_or_create(user=request.user, product=product)

    if not created:
        cart.quantity += 1
        cart.save()
    return redirect('shop')


@login_required(login_url='login')
def remove_wishlist_product(request, pk):
    product = get_object_or_404(product_version, id = pk)
    print(product)
    try:
        cart_items = Wishlist.objects.filter(user = request.user, product = product)
        product.save()
        cart_items.delete()
    except Wishlist.DoesNotExist:
        pass

    return redirect('wishlist')

@login_required(login_url='login')
def remove_cart_product(request, pk):
    product = get_object_or_404(product_version, id = pk)

    try:
        cart_items = Add_to_Cart.objects.filter(user = request.user, product = product)
        product.save()
        cart_items.delete()
    except Add_to_Cart.DoesNotExist:
        pass

    return redirect('cart')

shop/templates/product-details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


		<!-- End Header Area -->

		<!-- Main Menu Area -->
		<!-- End Main Menu Area -->
		<!-- Breadcurb Area -->
		<div class="breadcurb-area">
			<div class="container">
				<ul class="breadcrumb">
					<li class="home"><a href="{% url 'index' %}">Home</a></li>
				</ul>
			</div>
		</div><!-- End Breadcurb Area -->
		<!-- Single Product details Area -->
		<div class="single-product-detaisl-area">
			<!-- Single Product View Area -->
			<div class="single-product-view-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-5">
							<!-- Single Product View -->
							<div class="single-procuct-view">
								<!-- Simple Lence Gallery Container -->
								<div class="simpleLens-gallery-container" id="p-view">
									<div class="simpleLens-container tab-content">
										<div class="tab-pane active" id="p-view-1">
											<div class="simpleLens-big-image-container">
												<a class="simpleLens-lens-image" data-lens-image="assets/images/products/single-product/large/1.webp">
													<img src="{{product.cover_image.url}}" class="simpleLens-big-image" alt="productd">
												</a>
											</div>
										</div>
									</div>
									<div class="tab-pane" id="p-view-2">
										<div style="display: flex;" class="simpleLens-big-image-container">
											{% for image in product.images.all %}
											<a class="simpleLens-lens-image" data-lens-image="{{image.url}}">
												<img src="{{image.image.url}}" class="simpleLens-big-image" alt="productd">
											</a>
											{% endfor %}
										</div>
									</div>
									<!-- Simple Lence Thumbnail -->
									<div class="simpleLens-thumbnails-container">
										<div id="single-product" class="owl-carousel custom-carousel">
											<ul class="nav nav-tabs" role="tablist">
												<li><a class="active" href="#p-view-1" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/1.webp' %}" alt="productd"></a></li>
												<li class=""><a href="#p-view-2" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/2.webp' %}" alt="productd"></a></li>
												<li class="last-li"><a href="#p-view-3" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/3.webp' %}" alt="productd"></a></li>
												<li class="d-none d-xl-block"><a href="#p-view-4" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/4.webp' %}" alt="productd"></a></li>
											</ul>
											<ul class="nav nav-tabs" role="tablist">
												<li class=""><a class="active" href="#p-view-5" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/1.webp' %}"alt="productd"></a></li>
												<li class=""><a href="#p-view-6" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/2.webp' %}"alt="productd"></a></li>
												<li class="last-li"><a href="#p-view-7" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/3.webp' %}"alt="productd"></a></li>
												<li class="d-none d-xl-block"><a href="#p-view-8" role="tab" data-bs-toggle="tab"><img src="{% static 'images/products/single-product/thumbnail/4.webp' %}" alt="productd"></a></li>
											</ul>
										</div>
									</div><!-- End Simple Lence Thumbnail -->
								</div><!-- End Simple Lence Gallery Container -->
							</div><!-- End Single Product View -->
						</div>
						<div class="col-lg-7">
							<!-- Single Product Content View -->
							<div class="single-product-content-view">
								<div class="product-info">
									<h1>{{ product.product.title }}</h1>
									<p class="availability in-stock">Availability: {{product.product.availability}}<span></span></p>
									<div class="quick-desc">
										{{product.product.desc}}
									</div>
									<div class="price-box">
										<p class="price"><span class="special-price"><span class="amount">$ {{ product.product.price }}</span></span></p>
									</div>
								</div><!-- End product-info -->
								<!-- Add to Box -->
								<div class="add-to-box add-to-box2">
									<div class="actions-inner">
										<ul class="add-to-links">
											<li><a class="link-wishlist" title="Add to Wishlist" href=""><i class="fa fa-star"></i></a></li>
										</ul>
									</div>
									<div class="product-select product-color">
										<h2>Color <sup>*</sup></h2>
										<select onchange="window.location.href=this.value;">
											<option>--Please Select--</option>
											{% for color in colors %}
												<option value="/shop/productdetails/{{ color.pk }}/">{{color.color}}</option>
											{% endfor %}
										</select>
									</div>
									<div class="quick-add-to-cart">
										<form method="post" class="cart">
											<div class="qty-button"> 	
												<input type="text" class="input-text qty" title="Qty" value="1" maxlength="12" id="qty" name="qty">
												
												<div class="box-icon button-plus"> 
													<input type="button" class="qty-increase " onclick="var qty_el = document.getElementById('qty'); var qty = qty_el.value; if( !isNaN( qty )) qty_el.value++;return false;" value="+">
												</div>	
												<div class="box-icon button-minus">
													<input type="button" class="qty-decrease" onclick="var qty_el = document.getElementById('qty'); var qty = qty_el.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 0 ) qty_el.value--;return false;" value="-">
												</div>
											</div>
											<div class="product-actions">
												<button class="button btn-cart" title="Add to Cart" type="button"><a href='' class="fa fa-shopping-cart">&nbsp;</a><span>Add to Cart</span></button>
											</div>
										</form>
									</div>
								</div><!-- End Add to Box -->
								<!-- Social Shiring -->
								<div class="social-sharing">
									<a href="#"><img src="{% static 'images/icon/social.webp' %}" alt="social"></a>
								</div><!-- End Social Shiring -->
							</div><!-- End Single Product Content View -->
						</div>
					</div>
				</div>
			</div><!-- End Single Product View Area -->
			<!-- Single Description Tab -->
			<div class="single-product-description">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="product-description-tab custom-tab">
								<!-- tab bar -->
								<ul class="nav nav-tabs" role="tablist">
									<li><a class="active" href="#product-des" data-bs-toggle="tab">Product Description</a></li>
									<li><a href="#product-rev" data-bs-toggle="tab">Reviews</a></li>
									<li><a href="#product-tag" data-bs-toggle="tab">Product Tags</a></li>
								</ul>
								<!-- Tab Content -->
								<div class="tab-content">
									<div class="tab-pane active" id="product-des">
										<p>{{ product.product.desc }}</p>
									</div>
									<div class="tab-pane" id="product-rev">
										<div class="row">
											<div class="col-lg-6">
												<div class="product-rev-left">
													{% if not reviews  %}
														<p>Not review added yet...</p>
													{% else %}
													{% for review in reviews.all %}
													<p class="product-action">
														{{review.review}}
													</p>
													<div class="product-ratting">
														<table class="">
															<tr>
																<td>Quality</td>
																<td><div class="rating-box">
																	<div class="rating" style="width: {{ review.get_quality_review_display }}%;"></div>
																  </div></td>
															</tr>
															<tr>
																<td>Price</td>
																<td><div class="rating-box">
																	<div class="rating" style="width: {{ review.get_price_review_display }}%;"></div>
																  </div></td>
															</tr>
															<tr>
																<td>Value</td>
																<td><div class="rating-box">
																	<div class="rating" style="width: {{ review.get_value_review_display }}%;"></div>
																  </div></td>
															</tr>
														</table>
													</div>
													<p> Review by <b> {{review.nickname}} </b> <br> <span class="posted">{{review.date_added}}</span></p>
													{% endfor %}
													{% endif %}
												</div>
											</div>
											<div class="col-lg-6">
												<div class="product-rev-right">
													<h3>You're reviewing: {{ product.title }}</h3>
													<h3><b>How do you rate this product? <span>*</span></b></h3>
													<form method="POST">
														<div class="product-rev-right-table table-responsive">
															<table>
																<thead>
																	<tr class="first last">
																		<th>&nbsp;</th>
																		<th><span class="nobr">1 stars</span></th>
																		<th><span class="nobr">2 stars</span></th>
																		<th><span class="nobr">3 stars</span></th>
																		<th><span class="nobr">4 stars</span></th>
																		<th><span class="nobr">5 stars</span></th>
																	</tr>
																</thead>
																<tbody>
																	<tr>
																		<th>Quality</th>
																		<th><input type="radio" class="radio" name="quality_review" value="1"></th>
																		<th><input type="radio" class="radio" name="quality_review" value="2"></th>
																		<th><input type="radio" class="radio" name="quality_review" value="3"></th>
																		<th><input type="radio" class="radio" name="quality_review" value="4"></th>
																		<th><input type="radio" class="radio" name="quality_review" value="5"></th>
																	</tr>
																	<tr>
																		<th>Price</th>
																		<th><input type="radio" class="radio" name="price_review" value="1"></th>
																		<th><input type="radio" class="radio" name="price_review" value="2"></th>
																		<th><input type="radio" class="radio" name="price_review" value="3"></th>
																		<th><input type="radio" class="radio" name="price_review" value="4"></th>
																		<th><input type="radio" class="radio" name="price_review" value="5"></th>
																	</tr>
																	<tr>
																		<th>Value</th>
																		<th><input type="radio" class="radio" name="value_review" value="1"></th>
																		<th><input type="radio" class="radio" name="value_review" value="2"></th>
																		<th><input type="radio" class="radio" name="value_review" value="3"></th>
																		<th><input type="radio" class="radio" name="value_review" value="4"></th>
																		<th><input type="radio" class="radio" name="value_review" value="5"></th>
																	</tr>
																</tbody>
															</table>
														</div>
														<div class="porduct-rev-right-form">
																{% csrf_token %}
																<div class="form-group">
																	<label>Name <sup></sup></label>
																	{{ form.nickname }}
																</div>
																<div class="form-group">
																	<label>Review <sup></sup></label>
																	{{ form.review }}
																</div>
																<div class="form-group form-group-button">
																	<button class="btn custom-button" type="submit" value="Post Review">Submit Review</button>
																</div>
														</div>
													</form>
												</div>
											</div>
										</div>
									</div>
									<div class="tab-pane" id="product-tag">
										{% for tag in product.product.tag.all %}
										<p>{{ tag }}</p>
										{% endfor %}
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div><!-- End Single Description Tab -->
			<!-- Product Area -->
			<div class="product-area ">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<!-- Product View Area -->
						</div>
					</div>
				</div>
			</div><!-- End Product Area -->
		</div><!-- End Single Product details Area -->
		<!-- Brand Area -->
		<div class="brand-area">
			<div class="container">
				<div class="row">
					<div class="col-lg-4">
						<div class="brand-add">
							<a href="#"><img src="{% static 'images/brand-logo/bl5.webp' %}" alt="brand-logo"></a>
						</div>
					</div>
					<div class="col-lg-8">
						<!-- Brand Logo -->
						<div class="brand-logo">
							<div id="logo-carousel" class="owl-carousel">
								<a href="#"><img src="{% static 'images/brand-logo/bl1.webp' %}" alt="brand-logo"></a>
								<a href="#"><img src="{% static 'images/brand-logo/bl2.webp' %}"  alt="brand-logo"></a>
								<a href="#"><img src="{% static 'images/brand-logo/bl3.webp' %}"  alt="brand-logo"></a>
								<a href="#"><img src="{% static 'images/brand-logo/bl4.webp' %}"  alt="brand-logo"></a>
								<a href="#"><img src="{% static 'images/brand-logo/bl1.webp' %}"  alt="brand-logo"></a>
								<a href="#"><img src="{% static 'images/brand-logo/bl2.webp' %}"  alt="brand-logo"></a>
								<a href="#"><img src="{% static 'images/brand-logo/bl3.webp' %}"  alt="brand-logo"></a>
								<a href="#"><img src="{% static 'images/brand-logo/bl4.webp' %}"  alt="brand-logo"></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div><!-- End Brand Area -->	
		
		<!-- Footer Area -->
	

    </body>

<!-- Mirrored from htmldemo.net/selphy/selphy/product-details.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 08 Jun 2023 15:06:29 GMT -->
</html>
{% endblock %}